### ISSUE TITLE
Does it must have the GPU, can we use only CPU?

### ISSUE THREAD

**Issue by SeekPoint** [baidu-research/GloballyNormalizedReader#3]

**Comment by JonathanRaiman** [comment]
Training can be done on GPU or CPU, however the present code uses CuDNN LSTMs, which only have a kernel available on GPU. Of course you can switch to using tensor flow's `dynamic_rnn` and use another LSTMCell instead (see for instance the cell defined here https://www.tensorflow.org/tutorials/recurrent#lstm).
